from .plan_service import PlanService
from .grado_service import GradoService
from .facultad_service import FacultadService
from .universidad_service import UniversidadService
from .especialidad_service import EspecialidadService
from .orientaciones_services import OrientacionService
from .pais_service import PaisService
from .materia_service import MateriaService
from .localidad_service import LocalidadService
