from .plan_repository import PlanRepository
from .grado_repository import GradoRepository
from .universidad_repository import UniversidadRepository
from .especialidad_repository import EspecialidadRepository
from .materia_repository import MateriaRepository
from .localidad_repository import LocalidadRepository

